### ISSUE TITLE
Custom input select for temperature/ventilation mode

### ISSUE THREAD

**Issue by bj00rn** [bj00rn/ha-saleryd-ftx#18]
**Is your feature request related to a problem? Please describe.**
No way to set ventilation/temperature -mode using input select in HA

**Describe the solution you'd like**
Implement custom inout select

**Describe alternatives you've considered**
-

**Additional context**
Inspo: https://github.com/ThermIQ/thermiq_mqtt-ha/blob/91799864a2ee61a6e31711e2c60c34e2007bbc99/custom_components/thermiq_mqtt/input_select.py

**Comment by Fettkeewl** [comment]
Any progress on this? It's a wanted feature 😁

**Comment by bj00rn** [comment]
> Any progress on this? It's a wanted feature 😁

Not sure this is a good idea. Seems that the input_select keeps it's own state in HA somehow which complicates things, and input selects are not really good UX anyways imho. Feel free to dive into the thermiq implementation and do a PR if you wan't.  

At some point i had envisioned some kind of dashboard bundled with the integration, feel free to dive into that too.

You can do a enitity card that calls the set_ventilation_mode service until then:

https://community.home-assistant.io/t/call-service-button-from-lovelace/168656/7

**Comment by bindingofman** [comment]
![Screenshot_20231128_143740_Home Assistant](https://github.com/bj00rn/ha-saleryd-ftx/assets/109304754/5198bf6d-4e5d-4c5a-a8c1-6ab44d118eff)

I use the default settings and all works great for me, this is my card. It's a stock image and is just a representation. I have automations that are connected to temperature and humidity so the ftx will adjust to those conditions. Boost after shower and such.

**Comment by bj00rn** [comment]
> ![Screenshot_20231128_143740_Home Assistant](https://private-user-images.githubusercontent.com/109304754/287196875-5198bf6d-4e5d-4c5a-a8c1-6ab44d118eff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTc5MjMsIm5iZiI6MTcwMTQxNzYyMywicGF0aCI6Ii8xMDkzMDQ3NTQvMjg3MTk2ODc1LTUxOThiZjZkLTRlNWQtNGM1YS1hOGMxLTZhYjQ0ZDExOGVmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQwODAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDA2ZThhYWZjYmY4OWIwYzQ0NmE5Mjk1ODg5NjUzZDQ3ZTM1M2I5NzI0ZWQwYjI2YTdkMzA5MmUwNmM3NDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CNHh9eIljxDSRtfTjDgC6sKTz5dHZG49p6vAAer5x_o)
> 
> I use the default settings and all works great for me, this is my card. It's a stock image and is just a representation. I have automations that are connected to temperature and humidity so the ftx will adjust to those conditions. Boost after shower and such.

Sweet! Is it possible to bundle something like this with the integration you think?

**Comment by Fettkeewl** [comment]
> ![Screenshot_20231128_143740_Home Assistant](https://private-user-images.githubusercontent.com/109304754/287196875-5198bf6d-4e5d-4c5a-a8c1-6ab44d118eff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDY5MDEsIm5iZiI6MTcwMTUwNjYwMSwicGF0aCI6Ii8xMDkzMDQ3NTQvMjg3MTk2ODc1LTUxOThiZjZkLTRlNWQtNGM1YS1hOGMxLTZhYjQ0ZDExOGVmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQwODQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWQ4ZTI1YzUyMWQwZTU1NmUyNjAzM2I1YWVkMWVlZmI4N2NlMGIzZWM2MzU1OWUzNzBlZDM2ZjBjYTAyZWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P-YS3MtIW1nNQ6mQ0QTQVCCcLrh3jfGxl-LRDRrYAz0)
> 
> I use the default settings and all works great for me, this is my card. It's a stock image and is just a representation. I have automations that are connected to temperature and humidity so the ftx will adjust to those conditions. Boost after shower and such.

Care to share the yaml? I found the image as well. Neat.
Been playing with trying to get animations to work for fans and rotor, no luck sofar :P

**Comment by bindingofman** [comment]
> Care to share the yaml? I found the image as well. Neat. Been playing with trying to get animations to work for fans and rotor, no luck sofar :P

Hello, yes. 
This card is built up of custom:stack-in-card, custom:mushroom, and custom:button-card (this is the one for animating icons)
```yaml
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: switch.saleryd_hrv_away_mode
        name: Away
      - type: custom:button-card
        name: Boost
        entity: switch.saleryd_hrv_boost_mode
        state:
          - value: 'on'
            color: lightblue
            styles:
              icon:
                - animation: rotating 2s linear infinite
          - value: 'off'
            styles:
              icon:
                - animation: rotating 6s linear infinite
                 
```

The boost icon is revolving even when off, but when activated it changes color and goes faster.


```yaml
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        tap_action:
          action: call-service
          service: saleryd_hrv.set_temperature_mode
          target: {}
          data:
            value: 0
        icon: mdi:thermometer-chevron-up
        entity: sensor.saleryd_hrv_target_temperature
        state:
          - value: '21'
            color: light blue
          - value: '19'
            color: rgba(68,115,158)
          - value: '16'
            color: rgba(68,115,158)
        name: 21°C

```

Set temp icons calls the service for the 3 available temperatures.
This could/ probably should be tidied up, it was a year since I got the Saleryd machine and added the integration.
